### ISSUE TITLE
DOCS - Mongo Set up

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-mongo#1]
Hello @b3nhard 

Please add in this thread all the steps related to the Mongo & App Set up: 

- The `connection string`
- Things to be added to `env` 
- Other information that might help beginners to bootstrap without the drama 

Ty!

**Comment by b3nhard** [comment]
Hello   **@app-generator**

I have added all the steps required for a beginner to get started on the starter **template.**
Do I have to add docker setup?

**Comment by app-generator** [comment]
Hello @b3nhard 

We can do the Docker set UP later. 
Can you specify where are the DOCS committed? 

P.S. Is not about the code, is about `How to set up the project` 

For instance, where the app expects a MONGO service to be up and running?

**Comment by app-generator** [comment]
Ty @b3nhard
